### ISSUE TITLE
Error in netty code when running from PyXenon (with mutual TLS)

### ISSUE THREAD

**Issue by jhidding** [NLeSC/xenon-grpc#37]
Just starting the server in mutual TLS mode gives me this error.

```
Starting Xenon-GRPC server.
[out] 16:55:31.857 [main] ERROR n.e.xenon.grpc.XenonServerWrapper - Server started, listening on port 45727 with mutual TLS
[err] Exception in thread "main" java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.forEachByte(IILio/netty/util/ByteProcessor;)I
[err] at io.netty.handler.codec.base64.Base64$Decoder.decode(Base64.java:345)
[err] at io.netty.handler.codec.base64.Base64.decode(Base64.java:323)
[err] at io.netty.handler.codec.base64.Base64.decode(Base64.java:310)
[err] at io.netty.handler.codec.base64.Base64.decode(Base64.java:298)
[err] at io.netty.handler.codec.base64.Base64.decode(Base64.java:290)
[err] at io.netty.handler.ssl.PemReader.readCertificates(PemReader.java:90)
[err] at io.netty.handler.ssl.PemReader.readCertificates(PemReader.java:64)
[err] at io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1070)
[err] at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:260)
[err] at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:222)
[err] at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:54)
[err] at io.grpc.netty.GrpcSslContexts.forServer(GrpcSslContexts.java:104)
[err] at nl.esciencecenter.xenon.grpc.XenonServerWrapper.secureServerBuilder(XenonServerWrapper.java:178)
[err] at nl.esciencecenter.xenon.grpc.XenonServerWrapper.serverBuilder(XenonServerWrapper.java:111)
[err] at nl.esciencecenter.xenon.grpc.XenonServerWrapper.start(XenonServerWrapper.java:96)
[err] at nl.esciencecenter.xenon.grpc.XenonServerWrapper.main(XenonServerWrapper.java:50)
```

**Comment by sverhoeven** [comment]
A version conflict.
* grpc-netty depends on netty 4.1.17
* hadoop-hdfs depends on netty 3.7.0 and io.netty:netty-all:4.0.23.Final

I will exclude the hadoop-hdfs deps
